version: '3.2'
services:
  connect-example:
    build:
      context: ./connect-example
      args:
        - NODE_VER=16.17.1-slim
      dockerfile: Dockerfile
    volumes:
      - ./connect-example:/connect-example
    ports:
      - '5173:5173'
    tty: true
    command: "npm run dev"
    working_dir: /connect-example